language: c

sudo: false

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install protobuf
  - luarocks install luabitop
  - luarocks install luacov
  - luarocks install luacov-coveralls
  - luarocks install busted

#script:
#  - busted --coverage test/*.lua

#after_success:
#  - luacov-coveralls --exclude test --exclude ./install --verbose

notifications:
  email:
    on_success: change
    on_failure: always

